<a href="https://colab.research.google.com/github/patelsaumya/python-libraries/blob/main/Numpy_for_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Creating Arrays

## Explicitly Initialized Arrays


In [ ]:
ary = np.array([45,87,34, 5])
ary, ary.dtype, ary.ndim, ary.shape, ary.size, ary[2]

(array([45, 87, 34,  5]), dtype('int64'), 1, (4,), 4, 34)

In [ ]:
ary = np.array([[44,6,78,34],[23,78,90,78]], dtype='int32')
ary, ary.dtype, ary.ndim, ary.shape, ary.size, ary[1,3]

(array([[44,  6, 78, 34],
        [23, 78, 90, 78]], dtype=int32), dtype('int32'), 2, (2, 4), 8, 78)

## Create Identity Matrix


In [ ]:
np.eye(1)

array([[1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Diagonal Matrix

### Create Diagonal Matrix

In [ ]:
np.diag([1,5,7])

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 7]])

### Extract Diagonal from a given Matrix

In [ ]:
ary = np.array([[23,14,65], [345,78,90]])
np.diag(ary)

array([23, 78])

## Create Matrix of ones, zeros, empty, full w/wo like

### Without like i.e. using specific shape

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.full((2,3), 5)

array([[5, 5, 5],
       [5, 5, 5]])

### Using shape of other matrix i.e. with like

In [ ]:
ary = np.array([[23,14,65], [345,78,90]])
np.ones_like(ary)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
# Use with Caution
np.empty_like(ary)

array([[94851762600416,              0,              0],
       [             0,              0,              0]])

# Converting DataType of Arrays

In [ ]:
ary = np.eye(2)
ary, ary.dtype

(array([[1., 0.],
        [0., 1.]]), dtype('float64'))

In [ ]:
bry = ary.astype('int32')
bry

array([[1, 0],
       [0, 1]], dtype=int32)

In [ ]:
np.array([21, 32, None, 45])
# This cannot be converted to numeric array

array([21, 32, None, 45], dtype=object)

In [ ]:
ary = np.array([21, np.nan, 5, np.inf])
ary, ary.dtype
# Converting this to numeric array will replace nan and inf with random numbers

(array([21., nan,  5., inf]), dtype('float64'))

# Selection and Projection

## Selection and Projection using Indexed Arrays

### Get Rows using Indexed Array

In [ ]:
ary = np.array([[22,57,97,17],
               [45,78,34,19],
               [34,37,88,99]])
idx = np.array([0,2])
ary[idx]

array([[22, 57, 97, 17],
       [34, 37, 88, 99]])

### Get Columns using Indexed Array

In [ ]:
ary[:,idx]

array([[22, 97],
       [45, 34],
       [34, 88]])

## Selection and Projection using Masked Arrays

### Get Elements using Mask

In [ ]:
ary = np.array([22,57,79,17])
mask = np.array([False, True, True, False])
ary[mask]

array([57, 79])

In [ ]:
ary = np.array([[22,57,97,17],
               [45,78,34,19]])
mask = np.array([[False, True, True, False],
                 [False, True, False, True]])
ary[mask]

array([57, 97, 78, 19])

### Get Rows using Mask

In [ ]:
ary = np.array([[22,57,97,17],
               [45,78,34,19]])
mask = np.array([False, True])
ary[mask]

array([[45, 78, 34, 19]])

### Get Columns using Mask

In [ ]:
ary = np.array([[22,57,97,17],
               [45,78,34,19]])
mask = np.array([False, True, True, False])
ary[:,mask]

array([[57, 97],
       [78, 34]])

### Negate Masked Matrix

In [ ]:
mask = np.array([[False, True, True, False],
                 [True, False, True, False]])
~mask

array([[ True, False, False,  True],
       [False,  True, False,  True]])

## Get Mask Indices

In [87]:
mask = np.array([False, True, True, False])
print(np.where(mask), np.argwhere(mask), sep='\n')

(array([1, 2]),)
[[1]
 [2]]


In [91]:
mask = np.array([[False, True, True, False],
                 [True, False, True, False]])
print(np.where(mask), np.argwhere(mask), sep='\n')

(array([0, 0, 1, 1]), array([1, 2, 0, 2]))
[[0 1]
 [0 2]
 [1 0]
 [1 2]]


## Selection based on the Conditions

### Select the elements matching the condition

In [ ]:
ary = np.array([[11, 22, 33, 44],
                [55, 66, 77, 88],
                [12, 23, 78, 99]])
print(ary > 22, ary[ary > 22], sep='\n')

[[False False  True  True]
 [ True  True  True  True]
 [False  True  True  True]]
[33 44 55 66 77 88 23 78 99]


### Select the row if the corresponding column has a value matching the condition

In [ ]:
ary = np.array([[11, 22, 33, 44],
                [55, 66, 77, 88],
                [12, 23, 78, 99]])
mask = ary[:, 1] > 22
print(mask, ary[mask], sep='\n')

[False  True  True]
[[55 66 77 88]
 [12 23 78 99]]


### Select the row if it has any value matching the condition

In [ ]:
ary = np.array([[11, 22, 33, 44],
                [55, 66, 77, 88],
                [12, 23, 78, 99]])
mask = np.any(ary < 23, axis=1)
print(mask, ary[mask,:], sep='\n')

[ True False  True]
[[11 22 33 44]
 [12 23 78 99]]


### Select the column if it has any value matching the condition

In [ ]:
ary = np.array([[11, 22, 33, 44],
                [55, 66, 77, 88],
                [12, 23, 78, 99]])
mask = np.any(ary < 23, axis=0)
print(mask, ary[:,mask], sep='\n')

[ True  True False False]
[[11 22]
 [55 66]
 [12 23]]


# Missing Values: None, np.nan, np.inf

## Test for nan and inf

In [ ]:
np.nan == np.nan, np.nan is np.nan, np.nan in [np.nan]

(False, True, True)

In [ ]:
np.inf == np.inf, np.inf is np.inf, np.inf in [np.inf]

(True, True, True)

In [ ]:
None == None, None is None, None in [None]

(True, True, True)

## Select nan, inf

In [ ]:
ary = np.array([
  [ 1.     , 87.     , 57.54435],
  [ 2.     ,  8.     ,  7.31704],
  [ 3.     , 56.     , 56.82095],
  [ 4.     , 63.     , 64.15579],
  [ 5.     , np.nan  ,  5.74522],
  [ 6.     , 45.     , 19.56758],
  [ np.inf , 43.     , 39.62271],
  [ 8.     , 47.     , 34.95107],
  [ 9.     ,  2.     ,   np.nan],
  [10.     , 79.     , 36.41022],
  [11.     , 67.     , 49.83894],
  [12.     , 24.     ,   np.inf]])

In [ ]:
np.isnan(ary)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
np.isinf(ary)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [ True, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True]])

In [ ]:
np.isnan(ary).any(axis=1) #Rows with np.nan

array([False, False, False, False,  True, False, False, False,  True,
       False, False, False])

In [ ]:
np.isnan(ary).any(axis=0) #Columns with np.nan

array([False,  True,  True])

In [ ]:
ary[np.isnan(ary).any(axis=1)]

array([[5.     ,     nan, 5.74522],
       [9.     , 2.     ,     nan]])

In [ ]:
ary[:,np.isnan(ary).any(axis=0)]

array([[87.     , 57.54435],
       [ 8.     ,  7.31704],
       [56.     , 56.82095],
       [63.     , 64.15579],
       [     nan,  5.74522],
       [45.     , 19.56758],
       [43.     , 39.62271],
       [47.     , 34.95107],
       [ 2.     ,      nan],
       [79.     , 36.41022],
       [67.     , 49.83894],
       [24.     ,      inf]])