<a href="https://colab.research.google.com/github/patelsaumya/python-libraries/blob/main/Numpy_for_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Creating Arrays

#### Explicitly Initialized Arrays


In [2]:
ary = np.array([45,87,34, 5])
ary, ary.dtype, ary.ndim, ary.shape, ary.size, ary[2]

(array([45, 87, 34,  5]), dtype('int64'), 1, (4,), 4, 34)

In [3]:
ary = np.array([[44,6,78,34],[23,78,90,78]], dtype='int32')
ary, ary.dtype, ary.ndim, ary.shape, ary.size, ary[1,3]

(array([[44,  6, 78, 34],
        [23, 78, 90, 78]], dtype=int32), dtype('int32'), 2, (2, 4), 8, 78)

#### Create Identity Matrix


In [4]:
np.eye(1)

array([[1.]])

In [5]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Diagonal Matrix

###### Create Diagonal Matrix

In [47]:
np.diag([1,5,7])

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 7]])

###### Extract Diagonal from a given Matrix

In [48]:
ary = np.array([[23,14,65], [345,78,90]])
np.diag(ary)

array([23, 78])

#### Create Matrix of ones, zeros, empty, full w/wo like

###### Without like i.e. using specific shape

In [41]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.full((2,3), 5)

array([[5, 5, 5],
       [5, 5, 5]])

###### Using shape of other matrix i.e. with like

In [45]:
ary = np.array([[23,14,65], [345,78,90]])
np.ones_like(ary)

array([[1, 1, 1],
       [1, 1, 1]])

In [46]:
# Use with Caution
np.empty_like(ary)

array([[93963587024416,              0,              0],
       [             0,              0,              0]])

# Converting DataType of Arrays

In [14]:
ary = np.eye(2)
ary, ary.dtype

(array([[1., 0.],
        [0., 1.]]), dtype('float64'))

In [15]:
bry = ary.astype('int32')
bry

array([[1, 0],
       [0, 1]], dtype=int32)

In [16]:
np.array([21, 32, None, 45])
# This cannot be converted to numeric array

array([21, 32, None, 45], dtype=object)

In [17]:
ary = np.array([21, np.nan, 5, np.inf])
ary, ary.dtype
# Converting this to numeric array will replace nan and inf with random numbers

(array([21., nan,  5., inf]), dtype('float64'))

# Selection and Projection

#### Selection and Projection using Indexed Arrays

###### Get Rows using Indexed Array

In [18]:
ary = np.array([[22,57,97,17],
               [45,78,34,19],
               [34,37,88,99]])
idx = np.array([0,2])
ary[idx]

array([[22, 57, 97, 17],
       [34, 37, 88, 99]])

###### Get Columns using Indexed Array

In [19]:
ary[:,idx]

array([[22, 97],
       [45, 34],
       [34, 88]])

#### Selection and Projection using Masked Arrays

###### Get Elements using Mask

In [20]:
ary = np.array([22,57,79,17])
mask = np.array([False, True, True, False])
ary[mask]

array([57, 79])

In [21]:
ary = np.array([[22,57,97,17],
               [45,78,34,19]])
mask = np.array([[False, True, True, False],
                 [False, True, False, True]])
ary[mask]

array([57, 97, 78, 19])

###### Get Rows using Mask

In [22]:
ary = np.array([[22,57,97,17],
               [45,78,34,19]])
mask = np.array([False, True])
ary[mask]

array([[45, 78, 34, 19]])

###### Get Columns using Mask

In [23]:
ary = np.array([[22,57,97,17],
               [45,78,34,19]])
mask = np.array([False, True, True, False])
ary[:,mask]

array([[57, 97],
       [78, 34]])

###### Negate Masked Matrix

In [24]:
mask = np.array([[False, True, True, False],
                 [True, False, True, False]])
~mask

array([[ True, False, False,  True],
       [False,  True, False,  True]])

###### Create Masked Arrays using Conditions

In [25]:
ary = np.array([[11, 22, 33, 44],
                [55, 66, 77, 88]])
ary > 2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

###### Get Masked Indices

In [26]:
mask = np.array([False, True, True, False])
np.where(mask)

(array([1, 2]),)

In [27]:
np.argwhere(mask)

array([[1],
       [2]])

# Missing Values: None, np.nan, np.inf

#### Test for nan and inf

In [28]:
np.nan == np.nan, np.nan is np.nan, np.nan in [np.nan]

(False, True, True)

In [29]:
np.inf == np.inf, np.inf is np.inf, np.inf in [np.inf]

(True, True, True)

In [30]:
None == None, None is None, None in [None]

(True, True, True)

#### Select nan, inf

In [31]:
ary = np.array([
  [ 1.     , 87.     , 57.54435],
  [ 2.     ,  8.     ,  7.31704],
  [ 3.     , 56.     , 56.82095],
  [ 4.     , 63.     , 64.15579],
  [ 5.     , np.nan  ,  5.74522],
  [ 6.     , 45.     , 19.56758],
  [ np.inf , 43.     , 39.62271],
  [ 8.     , 47.     , 34.95107],
  [ 9.     ,  2.     ,   np.nan],
  [10.     , 79.     , 36.41022],
  [11.     , 67.     , 49.83894],
  [12.     , 24.     ,   np.inf]])

In [32]:
np.isnan(ary)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [33]:
np.isinf(ary)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [ True, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True]])