<a href="https://colab.research.google.com/github/patelsaumya/python-libraries/blob/main/Numpy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Setup

In [2]:
import numpy as np

In [3]:
ary = np.array([
  [ 1.     , 87.     , 57.54435],
  [ 2.     ,  8.     ,  7.31704],
  [ 3.     , 56.     , 56.82095],
  [ 4.     , 63.     , 64.15579],
  [ 5.     , 79      ,  5.74522],
  [ 6.     , 45.     , 19.56758],
  [ np.nan , 43.     , 39.62271],
  [ 8.     , 47.     , 34.95107],
  [ 9.     ,  2.     ,   np.nan],
  [10.     , 79.     , 36.41022],
  [11.     , 67.     , 49.83894],
  [12.     , 24.     ,   np.inf]])

## Find the indices of np.nan.

In [4]:
masked_nan = np.isnan(ary)
indices = np.argwhere(masked_nan)
print(indices)

[[6 0]
 [8 2]]


## Get all the numeric elements

In [5]:
masked_nan = np.isnan(ary)
masked_num = ~masked_nan
ary[masked_num]

array([ 1.     , 87.     , 57.54435,  2.     ,  8.     ,  7.31704,
        3.     , 56.     , 56.82095,  4.     , 63.     , 64.15579,
        5.     , 79.     ,  5.74522,  6.     , 45.     , 19.56758,
       43.     , 39.62271,  8.     , 47.     , 34.95107,  9.     ,
        2.     , 10.     , 79.     , 36.41022, 11.     , 67.     ,
       49.83894, 12.     , 24.     ,      inf])

# Get rows that donot have nan or inf

In [6]:
masked_nan_inf = np.any(np.isnan(ary) | np.isinf(ary), axis=1)
masked_num = ~masked_nan_inf
ary[masked_num,:]

array([[ 1.     , 87.     , 57.54435],
       [ 2.     ,  8.     ,  7.31704],
       [ 3.     , 56.     , 56.82095],
       [ 4.     , 63.     , 64.15579],
       [ 5.     , 79.     ,  5.74522],
       [ 6.     , 45.     , 19.56758],
       [ 8.     , 47.     , 34.95107],
       [10.     , 79.     , 36.41022],
       [11.     , 67.     , 49.83894]])

In [7]:
# Alternative Solution
row_indices = np.where(masked_num)
ary[row_indices]

array([[ 1.     , 87.     , 57.54435],
       [ 2.     ,  8.     ,  7.31704],
       [ 3.     , 56.     , 56.82095],
       [ 4.     , 63.     , 64.15579],
       [ 5.     , 79.     ,  5.74522],
       [ 6.     , 45.     , 19.56758],
       [ 8.     , 47.     , 34.95107],
       [10.     , 79.     , 36.41022],
       [11.     , 67.     , 49.83894]])

# Get column-wise data that have np.nan or np.inf

In [8]:
masked_nan = np.any(np.isnan(ary) | np.isinf(ary), axis = 0)
ary[:,masked_nan]

array([[ 1.     , 57.54435],
       [ 2.     ,  7.31704],
       [ 3.     , 56.82095],
       [ 4.     , 64.15579],
       [ 5.     ,  5.74522],
       [ 6.     , 19.56758],
       [     nan, 39.62271],
       [ 8.     , 34.95107],
       [ 9.     ,      nan],
       [10.     , 36.41022],
       [11.     , 49.83894],
       [12.     ,      inf]])

In [9]:
# Alternative Solution
col_indices = np.where(masked_nan)
ary[:,col_indices]

array([[[ 1.     , 57.54435]],

       [[ 2.     ,  7.31704]],

       [[ 3.     , 56.82095]],

       [[ 4.     , 64.15579]],

       [[ 5.     ,  5.74522]],

       [[ 6.     , 19.56758]],

       [[     nan, 39.62271]],

       [[ 8.     , 34.95107]],

       [[ 9.     ,      nan]],

       [[10.     , 36.41022]],

       [[11.     , 49.83894]],

       [[12.     ,      inf]]])