<a href="https://colab.research.google.com/github/patelsaumya/python-libraries/blob/main/Numpy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Setup

In [1]:
import numpy as np

In [2]:
ary = np.array([
  [ 1.     , 87.     , 57.54435],
  [ 2.     ,  8.     ,  7.31704],
  [ 3.     , 56.     , 56.82095],
  [ 4.     , 63.     , 64.15579],
  [ 5.     , 79      ,  5.74522],
  [ 6.     , 45.     , 19.56758],
  [ np.nan , 43.     , 39.62271],
  [ 8.     , 47.     , 34.95107],
  [ 9.     ,  2.     ,   np.nan],
  [10.     , 79.     , 36.41022],
  [11.     , 67.     , 49.83894],
  [12.     , 24.     ,   np.inf]])

## Find the indices of np.nan.

In [3]:
masked_nan = np.isnan(ary)
indices = np.argwhere(masked_nan)
print(indices)

[[6 0]
 [8 2]]


## Get all the numeric elements

In [4]:
masked_nan = np.isnan(ary)
masked_num = ~masked_nan
ary[masked_num]

array([ 1.     , 87.     , 57.54435,  2.     ,  8.     ,  7.31704,
        3.     , 56.     , 56.82095,  4.     , 63.     , 64.15579,
        5.     , 79.     ,  5.74522,  6.     , 45.     , 19.56758,
       43.     , 39.62271,  8.     , 47.     , 34.95107,  9.     ,
        2.     , 10.     , 79.     , 36.41022, 11.     , 67.     ,
       49.83894, 12.     , 24.     ,      inf])

# Get rows that donot have nan or inf

In [5]:
masked_ary = np.isnan(ary) | np.isinf(ary)
print(masked_ary)
print('---------')
masked_nan_inf = np.any(masked_ary, axis=1)
print(masked_nan_inf)
print('---------')
masked_num = ~masked_nan_inf
print(masked_num)
print('---------')
ary[masked_num,:]

[[False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [ True False False]
 [False False False]
 [False False  True]
 [False False False]
 [False False False]
 [False False  True]]
---------
[False False False False False False  True False  True False False  True]
---------
[ True  True  True  True  True  True False  True False  True  True False]
---------


array([[ 1.     , 87.     , 57.54435],
       [ 2.     ,  8.     ,  7.31704],
       [ 3.     , 56.     , 56.82095],
       [ 4.     , 63.     , 64.15579],
       [ 5.     , 79.     ,  5.74522],
       [ 6.     , 45.     , 19.56758],
       [ 8.     , 47.     , 34.95107],
       [10.     , 79.     , 36.41022],
       [11.     , 67.     , 49.83894]])

In [6]:
# Alternative Solution
row_indices = np.where(masked_num)
ary[row_indices]

array([[ 1.     , 87.     , 57.54435],
       [ 2.     ,  8.     ,  7.31704],
       [ 3.     , 56.     , 56.82095],
       [ 4.     , 63.     , 64.15579],
       [ 5.     , 79.     ,  5.74522],
       [ 6.     , 45.     , 19.56758],
       [ 8.     , 47.     , 34.95107],
       [10.     , 79.     , 36.41022],
       [11.     , 67.     , 49.83894]])

# Get column-wise data that donot have np.nan

In [7]:
masked_ary = np.isnan(ary)
print(masked_ary)
print('---------')
masked_nan = np.any(masked_ary, axis = 0)
print(masked_nan)
print('---------')
masked_num = ~masked_nan
print(masked_num)
print('---------')
ary[:,masked_num]

[[False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [ True False False]
 [False False False]
 [False False  True]
 [False False False]
 [False False False]
 [False False False]]
---------
[ True False  True]
---------
[False  True False]
---------


array([[87.],
       [ 8.],
       [56.],
       [63.],
       [79.],
       [45.],
       [43.],
       [47.],
       [ 2.],
       [79.],
       [67.],
       [24.]])

In [8]:
# Alternative Solution
col_indices = np.where(masked_num)
ary[:,col_indices]

array([[[87.]],

       [[ 8.]],

       [[56.]],

       [[63.]],

       [[79.]],

       [[45.]],

       [[43.]],

       [[47.]],

       [[ 2.]],

       [[79.]],

       [[67.]],

       [[24.]]])